### ISSUE TITLE
Return a read stream if output path is NULL

### ISSUE THREAD

**Issue by ScottyFillups** [ScottyFillups/simple-thumbnail#28]
**Is your feature request related to a problem? Please describe.**

I want to pipe thumbnail data to S3.

**Describe the solution you'd like**

If the user passes in `null` for the output path, `simple-thumbnail` will resolve to a read stream.

**Describe alternatives you've considered**

I've considered making the thumbnail size an option rather than an argument, and making the output path optional (undefined -> output a read stream), but I don't want to make a breaking change.

**Additional context**

http://tutturu.tv

Hype incoming :^)

**Comment by cmd430** [comment]
I got it to work with output streams, (not returning a stream just using one) 
https://github.com/cmd430/simple-thumbnail/commit/df17a33ca87cd94cbaa29a3308f3c366d2cd4ca1

**Comment by ScottyFillups** [comment]
Released in `1.4.0`! :tada: :clap: :tada:

Thanks cmd for your help :)
