### ISSUE TITLE
"path" argument for FFMPEG does not support paths with spaces on Win10

### ISSUE THREAD

**Issue by uplusion23** [ScottyFillups/simple-thumbnail#64]
**Describe the bug**
When the path for FFMPEG [using ffmpeg-static] has a space in the file path, thumbnail generation fails.

```js
const simple-thumbnail = require('simple-thumbnail')
const ffmpeg = require('ffmpeg-static');

genThumbnail('vid.mp4', 'vid.png', '250x?', { path: ffmpeg }).then(() => console.log('done!')).catch(err => console.error(err))
```

**Environment:**
 - OS: [e.g. Windows10 x64]

**Additional context**
Here is a snip of the error, with personal information truncated. 
```
C:\Users\{username}\Desktop\Path With Spaces\node_modules\ffmpeg-static\bin\win32\x64\ffmpeg.exe
Error: ffmpeg exited 1
ffmpeg stderr:

'C:\Users\{username}\Desktop\Path' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.<anonymous> (C:\Users\{username}\Desktop\Outlook Test\node_modules\simple-thumbnail\index.js:101:21)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

**Comment by Ambyjkl** [comment]
:rofl: philip dude fix your newbie mistakes

**Comment by ScottyFillups** [comment]
Hi @uplusion23, I'll try to fix this tonight. Thanks for making the issue :smile:

**Comment by uplusion23** [comment]
> Hi @uplusion23, I'll try to fix this tonight. Thanks for making the issue 😄

No problem! Thanks for the simple plugin. Good work! Fixed it on my end, but my knowledge of Git is not good enough to make a commit request.

**Comment by ScottyFillups** [comment]
@uplusion23 Can you please confirm the fix works on your end?

**Comment by uplusion23** [comment]
> @uplusion23 Can you please confirm the fix works on your end?

Hey! Sorry for the delay, working with a few K/s where I am. My end seemed to work fine after installing the new version!
