### ISSUE TITLE
ffmpeg Issue

### ISSUE THREAD

**Issue by pratibha05sharma09** [ScottyFillups/simple-thumbnail#74]
**Describe the bug**
I am getting error ffmpeg: not found

**To Reproduce**
Code snippet or repository link that reproduces the error:

const simple-thumbnail = require('simple-thumbnail')

// Do stuff that breaks things!
``` genThumbnail('https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4', 'path.png', '250x250')
    .then(() => console.log('done!'))
    .catch(err => console.error(err))
```js

**Expected behavior**
An image will produce will name path.png but getting error  ffmpeg: not found. I also installed `ffmpeg-static` module.

**Environment (please complete the following information):**
 - OS: [e.g. Linux x64]
 - Version (ffmpeg): [e.g. 4.0.2]
 - Linking: [e.g. Static]

**Additional context**
Add any other context about the problem here.

**Comment by philipjscott** [comment]
You need to pass in `path` in the options:

```js
const ffmpeg = require('ffmpeg-static')
const genThumbnail = require('simple-thumbnail')

async function download () {
  await genThumbnail('https://www.w3schools.com/Html/mov_bbb.webm', 'bunny.webm', '150x?', {
    path: ffmpeg.path
  })
  
  console.log('Done!')
}

download()
```

**Comment by philipjscott** [comment]
Let me know if that works for you!

**Comment by pratibha05sharma09** [comment]
> Let me know if that works for you!

Hello  @ScottyFillups , Thanks for your response. I tried the solution provided by you. 
`const ffmpeg = require('ffmpeg-static')
const genThumbnail = require('simple-thumbnail')

async function download () {
  await genThumbnail('https://www.w3schools.com/Html/mov_bbb.webm', 'bunny.webm', '150x?', {
    path: ffmpeg.path
  })
  
  console.log('Done!')
}

download()`

But still getting the error **ffmpeg: not found** . To implement this functionality, I have to install the ffmpeg on my server with command `sudo apt-get install ffmpeg`. Please let me know, to do this without installing it on the server.

**Comment by philipjscott** [comment]
Ah! It seems that the `ffmpeg-static` changed. https://www.npmjs.com/package/ffmpeg-static

This code should work:

```js
const ffmpegPath = require('ffmpeg-static')
const genThumbnail = require('simple-thumbnail')

async function download () {
  await genThumbnail('https://www.w3schools.com/Html/mov_bbb.webm', 'bunny.webm', '150x?', {
    path: ffmpegPath
  })
}

download().then(() => console.log('done'))
```

**Comment by philipjscott** [comment]
Let me know if that works!

**Comment by pratibha05sharma09** [comment]
@ScottyFillups Thanks for your response. Yes the above code is working fine.
