### ISSUE TITLE
Thumbnail generate from pdf url

### ISSUE THREAD

**Issue by pratibha05sharma09** [ScottyFillups/simple-thumbnail#75]
I want to create the thumbnail of the pdf `https://firebasestorage.googleapis.com/v0/b/bond-core-demo.appspot.com/o/files%2Fuser_files%2FcHUN6D4MLRcEr2Bd3P3k%2FKnowledge%20Destinations%20-%20by%20tmf%20dialogue%20english.pdf?alt=media&token=6f23ebb8-5df9-4f14-8700-b18d135d8851`. How can i do this using this module?

**Comment by philipjscott** [comment]
Sorry I don't believe this module supports PDFs; you can try, but I don't think it'll work. I'm currently busy with other things so I won't be able to add support :x

**Comment by philipjscott** [comment]
If this is a one-off task (ie. you don't need to do it programmatically), there are many other tools that can help you :smile:

Check out https://superuser.com/questions/185880/how-to-convert-a-pdf-document-to-png
